apiVersion: apps/v1
kind: Deployment
metadata: 
  name: book-social-network
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-social-network
  template:
    metadata:
      labels:
        app: book-social-network
    spec: 
      containers:
        - name: app
          image: gcr.io/${PROJECT_ID}/${IMAGE}:${TAG}
          imagePullPolicy: Always